apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: TeamDman9201@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: cert-manager-issuer-account-key-staging
    solvers:
    - dns01:
        azureDNS:
          subscriptionID: 134ae9a1-7bc2-41f7-a2c7-a1e55f54ed04
          resourceGroupName: ca.teamdman
          hostedZoneName: teamdman.ca
          environment: AzurePublicCloud
          managedIdentity:
            clientID: ebc79310-5b30-4caf-9bfc-2c7f9c36353a
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: TeamDman9201@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: cert-manager-issuer-account-key-prod
    solvers:
    - selector: {}
      dns01:
        azureDNS:
          subscriptionID: 134ae9a1-7bc2-41f7-a2c7-a1e55f54ed04
          resourceGroupName: ca.teamdman
          hostedZoneName: teamdman.ca
          environment: AzurePublicCloud
          managedIdentity:
            clientID: ebc79310-5b30-4caf-9bfc-2c7f9c36353a