apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- base/certificate.yaml
- base/ingress.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml

patchesStrategicMerge:
- overlays/argocd-cm.yaml
# patchesStrategicMerge:
# - overlays/production/argo-cd-cm.yaml
# - overlays/production/argocd-server-service.yaml
# - overlays/production/argocd-repo-server-deploy.yaml


