apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: blob-fuse
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: unique-volumeid
    volumeAttributes:
      resourceGroup: net.azurewebsiets
      storageAccount: azurewebsiets
      containerName: content
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-storage
  # annotations:
  #   volume.beta.kubernetes.io/storage-class: blob-fuse
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: blob-fuse
  volumeName: pv-blob
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beans
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: beans
  template:
    metadata:
      labels: 
        app: beans
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: beancon
          image: nginx:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/var/www/html"
              name: persistent-storage
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: persistent-storage
