apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- base/core/project-core.yaml
- base/core/app-argocd.yaml
- base/core/app-app-of-apps.yaml
- base/core/app-blob-csi-driver.yaml
- base/core/app-cert-manager.yaml
- base/teamdman/project-teamdman.yaml
- base/teamdman/app-teamdman-www.yaml
- base/teamdman/app-external-dns-teamdman.yaml