apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- base/project-core.yaml
- base/app-argocd.yaml
- base/app-app-of-apps.yaml
- base/app-blob-csi-driver.yaml