apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- base/core/project-core.yaml
- base/core/app-argocd.yaml
- base/core/app-app-of-apps.yaml
- base/core/app-blob-csi-driver.yaml
- base/core/app-cert-manager.yaml
- base/core/app-external-secrets.yaml
- base/core/app-external-dns-teamdman.yaml
# - base/core/app-ingress-nginx.yaml
- base/teamdman/project-teamdman.yaml
- base/teamdman/app-teamdman-www.yaml
- base/azurewebsiets/project-azurewebsiets.yaml
- base/azurewebsiets/app-azurewebsiets-www.yaml
- base/azurewebsiets/app-azurewebsiets-dns.yaml