apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## don't specify namespace
## https://github.com/cert-manager/cert-manager/issues/5471
# namespace: cert-manager

# resources:
# - https://github.com/cert-manager/cert-manager/releases/download/v1.10.1/cert-manager.yaml
# --cluster-issuer-ambient-credentials     
# --issuer-ambient-credentials    

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.8.2
  releaseName: cert-manager
  valuesInline:
    installCRDs: true
    extraArgs:
    - --cluster-issuer-ambient-credentials
    - --issuer-ambient-credentials