apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-forwarder
  labels:
    app: email-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
        app: email-forwarder
  template:
    metadata:
      labels:
        app: email-forwarder
    spec:
      containers:
      - name: email-forwarder
        image: zixia/simple-mail-forwarder:1.4
        ports:
        - containerPort: 25
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mail-forwarder
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 25
