apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cd-cert
spec:
  secretName: argocd-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
    # name: letsencrypt-staging
    # name: selfsigned-issuer
  commonName: argocd.teamdman.ca
  dnsNames:
  - argocd.teamdman.ca
  - temp1.teamdman.ca
