apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: argo-cd-cert
spec:
  secretName: argocd-secret
  issuerRef:
    name: argo-cd-issuer
    kind: Issuer
  commonName: argocd.teamdman.ca
  dnsNames:
  - argocd.teamdman.ca
